// web/src/app/features/settings/settings.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';

import { AuthService } from '../../core/auth.service';
import { StoreService } from '../../core/store.service';

@Component({
  selector: 'app-settings',
  imports: [FormsModule],
  template: `
    <div class="form-narrow card">
      <h3>Account</h3>
      <p class="muted">{{ auth.user()?.email ?? '—' }}</p>

      <h3>Store details</h3>
      <label class="field">
        <span class="field-label">Store Name *</span>
        <input class="field-input" [(ngModel)]="name" />
      </label>
      <label class="field">
        <span class="field-label">Address</span>
        <textarea class="field-textarea" [(ngModel)]="address" placeholder="Store address"></textarea>
      </label>
      <label class="field">
        <span class="field-label">Phone</span>
        <input class="field-input" type="tel" [(ngModel)]="phone" />
      </label>
      <label class="field">
        <span class="field-label">Tax Rate (%)</span>
        <input class="field-input" type="number" [(ngModel)]="taxRate" />
      </label>
      <p class="muted">Currency: {{ store.store()?.currency ?? 'INR' }} · Shown on receipts</p>

      <button class="btn" type="button" [disabled]="saving" (click)="save()">
        @if (saving) {
          <span class="spinner"></span>
        }
        Save Settings
      </button>
      <button class="btn btn-danger" style="margin-top:24px;width:100%" type="button" (click)="signOut()">
        Sign Out
      </button>
    </div>
  `,
})
export class SettingsComponent implements OnInit {
  readonly auth = inject(AuthService);
  readonly store = inject(StoreService);
  private readonly router = inject(Router);

  name = '';
  address = '';
  phone = '';
  taxRate = '0';
  saving = false;

  ngOnInit(): void {
    const store = this.store.store();
    if (!store) return;
    this.name = store.name;
    this.address = store.address ?? '';
    this.phone = store.phone ?? '';
    this.taxRate = String(store.tax_rate);
  }

  async save(): Promise<void> {
    if (!this.name.trim()) {
      alert('Store name is required');
      return;
    }
    const tax = parseFloat(this.taxRate);
    if (isNaN(tax) || tax < 0 || tax > 100) {
      alert('Tax rate must be between 0 and 100');
      return;
    }

    this.saving = true;
    const { error } = await this.store.updateStore({
      name: this.name.trim(),
      address: this.address.trim() || null,
      phone: this.phone.trim() || null,
      tax_rate: tax,
    });
    this.saving = false;

    if (error) {
      alert(error);
      return;
    }
    alert('Store settings updated');
  }

  async signOut(): Promise<void> {
    if (!confirm('Are you sure you want to sign out?')) return;
    await this.auth.signOut();
    await this.router.navigateByUrl('/login');
  }
}

// mobile/app/(app)/settings.tsx
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import {
  Alert,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
} from 'react-native';

import { Button } from '@/components/Button';
import { Input } from '@/components/Input';
import { colors, fontSize, spacing } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';
import { useStore } from '@/context/StoreContext';

export default function SettingsScreen() {
  const { signOut, user } = useAuth();
  const { store, updateStore } = useStore();

  const [name, setName] = useState('');
  const [address, setAddress] = useState('');
  const [phone, setPhone] = useState('');
  const [taxRate, setTaxRate] = useState('0');
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (!store) return;
    setName(store.name);
    setAddress(store.address ?? '');
    setPhone(store.phone ?? '');
    setTaxRate(String(store.tax_rate));
  }, [store]);

  const handleSave = async () => {
    if (!name.trim()) {
      Alert.alert('Error', 'Store name is required');
      return;
    }

    const tax = parseFloat(taxRate);
    if (isNaN(tax) || tax < 0 || tax > 100) {
      Alert.alert('Error', 'Tax rate must be between 0 and 100');
      return;
    }

    setSaving(true);
    const { error } = await updateStore({
      name: name.trim(),
      address: address.trim() || null,
      phone: phone.trim() || null,
      tax_rate: tax,
    });
    setSaving(false);

    if (error) {
      Alert.alert('Save failed', error);
      return;
    }

    Alert.alert('Saved', 'Store settings updated');
  };

  const handleSignOut = () => {
    Alert.alert('Sign out', 'Are you sure you want to sign out?', [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Sign out',
        style: 'destructive',
        onPress: async () => {
          await signOut();
          router.replace('/');
        },
      },
    ]);
  };

  return (
    <KeyboardAvoidingView
      style={styles.flex}
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
      <ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled">
        <Text style={styles.sectionTitle}>Account</Text>
        <Text style={styles.email}>{user?.email ?? '—'}</Text>

        <Text style={styles.sectionTitle}>Store details</Text>
        <Input label="Store Name *" value={name} onChangeText={setName} />
        <Input
          label="Address"
          value={address}
          onChangeText={setAddress}
          multiline
          placeholder="Store address"
        />
        <Input
          label="Phone"
          value={phone}
          onChangeText={setPhone}
          keyboardType="phone-pad"
        />
        <Input
          label="Tax Rate (%)"
          value={taxRate}
          onChangeText={setTaxRate}
          keyboardType="decimal-pad"
        />

        <Text style={styles.hint}>
          Currency: {store?.currency ?? 'INR'} · Shown on receipts
        </Text>

        <Button title="Save Settings" onPress={handleSave} loading={saving} />
        <Button
          title="Sign Out"
          variant="danger"
          onPress={handleSignOut}
          style={styles.signOut}
        />
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  flex: { flex: 1 },
  container: {
    padding: spacing.lg,
    backgroundColor: colors.background,
  },
  sectionTitle: {
    fontSize: fontSize.md,
    fontWeight: '700',
    color: colors.text,
    marginBottom: spacing.sm,
    marginTop: spacing.md,
  },
  email: {
    fontSize: fontSize.md,
    color: colors.textSecondary,
    marginBottom: spacing.md,
  },
  hint: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
    marginBottom: spacing.lg,
  },
  signOut: {
    marginTop: spacing.lg,
  },
});
