// mobile/app/(auth)/login.tsx
import { Link, router } from 'expo-router';
import { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';

import { AuthShell } from '@/components/AuthShell';
import { Button } from '@/components/Button';
import { FormMessage } from '@/components/FormMessage';
import { Input } from '@/components/Input';
import { fontSize, spacing } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';
import { isSupabaseConfigured } from '@/lib/supabase';

export default function LoginScreen() {
  const { signIn } = useAuth();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  if (!isSupabaseConfigured) {
    return (
      <View style={styles.setup}>
        <Text style={styles.setupTitle}>Setup Required</Text>
        <Text style={styles.setupText}>
          Add your Supabase credentials to mobile/.env before signing in.
        </Text>
        <Link href="/(auth)/setup" asChild>
          <Button title="View Setup Instructions" />
        </Link>
      </View>
    );
  }

  const handleLogin = async () => {
    setError(null);

    if (!email.trim() || !password) {
      setError('Please enter email and password.');
      return;
    }

    setLoading(true);
    try {
      const { error: signInError } = await signIn(email.trim(), password);
      if (signInError) {
        setError(signInError);
        return;
      }
      router.replace('/');
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <AuthShell title="Sign In" subtitle="Sign in to manage your store">
      <Input
        label="Email"
        value={email}
        onChangeText={setEmail}
        autoCapitalize="none"
        keyboardType="email-address"
        autoComplete="email"
        placeholder="you@store.com"
      />
      <Input
        label="Password"
        value={password}
        onChangeText={setPassword}
        secureTextEntry
        autoComplete="password"
        placeholder="Your password"
      />

      <FormMessage error={error} />

      <Button title="Sign In" onPress={handleLogin} loading={loading} />

      <Link href="/(auth)/register" asChild>
        <Button title="Create Account" variant="outline" style={styles.linkBtn} />
      </Link>
    </AuthShell>
  );
}

const styles = StyleSheet.create({
  setup: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xl,
  },
  setupTitle: {
    fontSize: fontSize.xl,
    fontWeight: '800',
    marginBottom: spacing.sm,
  },
  setupText: {
    textAlign: 'center',
    marginBottom: spacing.lg,
  },
  linkBtn: {
    marginTop: spacing.md,
  },
});

// web/src/app/features/auth/login.component.ts
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';

import { AuthService } from '../../core/auth.service';
import { isSupabaseConfigured } from '../../core/supabase.client';

@Component({
  selector: 'app-login',
  imports: [FormsModule, RouterLink],
  template: `
    <div class="auth-shell">
      <div class="auth-card">
        @if (!configured) {
          <h1>Setup Required</h1>
          <p class="subtitle">Add your Supabase credentials to web/src/environments/environment.ts before signing in.</p>
          <a class="btn" routerLink="/setup">View Setup Instructions</a>
        } @else {
          <h1>Sign In</h1>
          <p class="subtitle">Sign in to manage your store</p>

          <label class="field">
            <span class="field-label">Email</span>
            <input class="field-input" type="email" [(ngModel)]="email" autocomplete="email" placeholder="you@store.com" />
          </label>
          <label class="field">
            <span class="field-label">Password</span>
            <input class="field-input" type="password" [(ngModel)]="password" autocomplete="current-password" placeholder="Your password" />
          </label>

          @if (error) {
            <p class="form-error">{{ error }}</p>
          }

          <button class="btn" type="button" [disabled]="loading" (click)="submit()">
            @if (loading) {
              <span class="spinner"></span>
            }
            Sign In
          </button>
          <a class="btn btn-outline" style="margin-top:16px;width:100%" routerLink="/register">Create Account</a>
        }
      </div>
    </div>
  `,
})
export class LoginComponent {
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);

  readonly configured = isSupabaseConfigured;
  email = '';
  password = '';
  loading = false;
  error: string | null = null;

  async submit(): Promise<void> {
    this.error = null;
    if (!this.email.trim() || !this.password) {
      this.error = 'Please enter email and password.';
      return;
    }

    this.loading = true;
    try {
      const { error } = await this.auth.signIn(this.email.trim(), this.password);
      if (error) {
        this.error = error;
        return;
      }
      await this.router.navigateByUrl('/');
    } catch (e) {
      this.error = e instanceof Error ? e.message : 'Something went wrong. Please try again.';
    } finally {
      this.loading = false;
    }
  }
}
