// mobile/app/(auth)/register.tsx
import { Link, router } from 'expo-router';
import { useState } from 'react';
import { StyleSheet } from 'react-native';

import { AuthShell } from '@/components/AuthShell';
import { Button } from '@/components/Button';
import { FormMessage } from '@/components/FormMessage';
import { Input } from '@/components/Input';
import { spacing } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';
import { showAlert } from '@/lib/alert';
import { isSupabaseConfigured } from '@/lib/supabase';

export default function RegisterScreen() {
  const { signUp } = useAuth();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleRegister = async () => {
    setError(null);

    if (!isSupabaseConfigured) {
      setError('Supabase is not configured. Check mobile/.env and restart the app.');
      return;
    }

    if (!email.trim() || !password || !confirmPassword) {
      setError('Please fill in all fields.');
      return;
    }
    if (password.length < 6) {
      setError('Password must be at least 6 characters.');
      return;
    }
    if (password !== confirmPassword) {
      setError('Passwords do not match.');
      return;
    }

    setLoading(true);
    try {
      const result = await signUp(email.trim(), password);

      if (result.error) {
        setError(result.error);
        return;
      }

      if (result.needsEmailConfirmation) {
        showAlert(
          'Confirm your email',
          'We sent a confirmation link to your email. Click it, then come back and sign in.',
          () => router.replace('/(auth)/login')
        );
        return;
      }

      router.replace('/');
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <AuthShell title="Create Account" subtitle="Start billing for your store">
      <Input
        label="Email"
        value={email}
        onChangeText={setEmail}
        autoCapitalize="none"
        keyboardType="email-address"
        autoComplete="email"
        placeholder="you@store.com"
      />
      <Input
        label="Password"
        value={password}
        onChangeText={setPassword}
        secureTextEntry
        placeholder="At least 6 characters"
      />
      <Input
        label="Confirm Password"
        value={confirmPassword}
        onChangeText={setConfirmPassword}
        secureTextEntry
        placeholder="Repeat password"
      />

      <FormMessage error={error} />

      <Button title="Create Account" onPress={handleRegister} loading={loading} />

      <Link href="/(auth)/login" asChild>
        <Button title="Back to Sign In" variant="outline" style={styles.linkBtn} />
      </Link>
    </AuthShell>
  );
}

const styles = StyleSheet.create({
  linkBtn: {
    marginTop: spacing.md,
  },
});

// web/src/app/features/auth/register.component.ts
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';

import { AuthService } from '../../core/auth.service';
import { isSupabaseConfigured } from '../../core/supabase.client';

@Component({
  selector: 'app-register',
  imports: [FormsModule, RouterLink],
  template: `
    <div class="auth-shell">
      <div class="auth-card">
        <h1>Create Account</h1>
        <p class="subtitle">Start billing for your store</p>

        <label class="field">
          <span class="field-label">Email</span>
          <input class="field-input" type="email" [(ngModel)]="email" autocomplete="email" placeholder="you@store.com" />
        </label>
        <label class="field">
          <span class="field-label">Password</span>
          <input class="field-input" type="password" [(ngModel)]="password" placeholder="At least 6 characters" />
        </label>
        <label class="field">
          <span class="field-label">Confirm Password</span>
          <input class="field-input" type="password" [(ngModel)]="confirmPassword" placeholder="Repeat password" />
        </label>

        @if (error) {
          <p class="form-error">{{ error }}</p>
        }

        <button class="btn" type="button" [disabled]="loading" (click)="submit()">
          @if (loading) {
            <span class="spinner"></span>
          }
          Create Account
        </button>
        <a class="btn btn-outline" style="margin-top:16px;width:100%" routerLink="/login">Back to Sign In</a>
      </div>
    </div>
  `,
})
export class RegisterComponent {
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);

  email = '';
  password = '';
  confirmPassword = '';
  loading = false;
  error: string | null = null;

  async submit(): Promise<void> {
    this.error = null;

    if (!isSupabaseConfigured) {
      this.error = 'Supabase is not configured. Check web/src/environments/environment.ts and restart the app.';
      return;
    }
    if (!this.email.trim() || !this.password || !this.confirmPassword) {
      this.error = 'Please fill in all fields.';
      return;
    }
    if (this.password.length < 6) {
      this.error = 'Password must be at least 6 characters.';
      return;
    }
    if (this.password !== this.confirmPassword) {
      this.error = 'Passwords do not match.';
      return;
    }

    this.loading = true;
    try {
      const result = await this.auth.signUp(this.email.trim(), this.password);
      if (result.error) {
        this.error = result.error;
        return;
      }
      if (result.needsEmailConfirmation) {
        alert('We sent a confirmation link to your email. Click it, then come back and sign in.');
        await this.router.navigateByUrl('/login');
        return;
      }
      await this.router.navigateByUrl('/');
    } catch (e) {
      this.error = e instanceof Error ? e.message : 'Something went wrong. Please try again.';
    } finally {
      this.loading = false;
    }
  }
}
