// mobile/app/(auth)/store-setup.tsx
import { router } from 'expo-router';
import { useState } from 'react';
import { StyleSheet } from 'react-native';

import { AuthShell } from '@/components/AuthShell';
import { Button } from '@/components/Button';
import { FormMessage } from '@/components/FormMessage';
import { Input } from '@/components/Input';
import { useStore } from '@/context/StoreContext';

export default function StoreSetupScreen() {
  const { createStore } = useStore();
  const [name, setName] = useState('');
  const [address, setAddress] = useState('');
  const [phone, setPhone] = useState('');
  const [taxRate, setTaxRate] = useState('0');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async () => {
    setError(null);

    if (!name.trim()) {
      setError('Store name is required.');
      return;
    }

    const tax = parseFloat(taxRate) || 0;
    if (tax < 0 || tax > 100) {
      setError('Tax rate must be between 0 and 100.');
      return;
    }

    setLoading(true);
    try {
      const { error: createError } = await createStore({
        name: name.trim(),
        address: address.trim() || undefined,
        phone: phone.trim() || undefined,
        tax_rate: tax,
        currency: 'INR',
      });

      if (createError) {
        setError(createError);
        return;
      }

      router.replace('/');
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <AuthShell title="Set Up Your Store" subtitle="This info appears on your receipts">
      <Input
        label="Store Name *"
        value={name}
        onChangeText={setName}
        placeholder="My Retail Store"
      />
      <Input
        label="Address"
        value={address}
        onChangeText={setAddress}
        placeholder="123 Main Street"
        multiline
      />
      <Input
        label="Phone"
        value={phone}
        onChangeText={setPhone}
        keyboardType="phone-pad"
        placeholder="+91 98765 43210"
      />
      <Input
        label="Tax Rate (%)"
        value={taxRate}
        onChangeText={setTaxRate}
        keyboardType="decimal-pad"
        placeholder="18"
      />

      <FormMessage error={error} />

      <Button title="Continue" onPress={handleSubmit} loading={loading} />
    </AuthShell>
  );
}

const styles = StyleSheet.create({});

// web/src/app/features/auth/store-setup.component.ts
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';

import { StoreService } from '../../core/store.service';

@Component({
  selector: 'app-store-setup',
  imports: [FormsModule],
  template: `
    <div class="auth-shell">
      <div class="auth-card">
        <h1>Set Up Your Store</h1>
        <p class="subtitle">This info appears on your receipts</p>

        <label class="field">
          <span class="field-label">Store Name *</span>
          <input class="field-input" [(ngModel)]="name" placeholder="My Retail Store" />
        </label>
        <label class="field">
          <span class="field-label">Address</span>
          <textarea class="field-textarea" [(ngModel)]="address" placeholder="123 Main Street"></textarea>
        </label>
        <label class="field">
          <span class="field-label">Phone</span>
          <input class="field-input" type="tel" [(ngModel)]="phone" placeholder="+91 98765 43210" />
        </label>
        <label class="field">
          <span class="field-label">Tax Rate (%)</span>
          <input class="field-input" type="number" [(ngModel)]="taxRate" placeholder="18" />
        </label>

        @if (error) {
          <p class="form-error">{{ error }}</p>
        }

        <button class="btn" type="button" [disabled]="loading" (click)="submit()">
          @if (loading) {
            <span class="spinner"></span>
          }
          Continue
        </button>
      </div>
    </div>
  `,
})
export class StoreSetupComponent {
  private readonly stores = inject(StoreService);
  private readonly router = inject(Router);

  name = '';
  address = '';
  phone = '';
  taxRate = '0';
  loading = false;
  error: string | null = null;

  async submit(): Promise<void> {
    this.error = null;
    if (!this.name.trim()) {
      this.error = 'Store name is required.';
      return;
    }

    const tax = parseFloat(this.taxRate) || 0;
    if (tax < 0 || tax > 100) {
      this.error = 'Tax rate must be between 0 and 100.';
      return;
    }

    this.loading = true;
    try {
      const { error } = await this.stores.createStore({
        name: this.name.trim(),
        address: this.address.trim() || undefined,
        phone: this.phone.trim() || undefined,
        tax_rate: tax,
        currency: 'INR',
      });
      if (error) {
        this.error = error;
        return;
      }
      await this.router.navigateByUrl('/');
    } catch (e) {
      this.error = e instanceof Error ? e.message : 'Something went wrong. Please try again.';
    } finally {
      this.loading = false;
    }
  }
}
